### ISSUE TITLE
1. initial-app

### ISSUE THREAD

**Issue by Sayed94h** [Sayed94h/restful-courses#3]
### Task A: HTML

- [x] Added `head tag`, `title tag`, `meta tags`
- [x] Added `header tag`
- [x] Added `h tags`
- [x] Added `section tags`
- [x] Added `input tags`
- [x] Added `main tag`
- [x] Added `button tag`
- [x] Added `script tag`
- [x] Linked the css style file
- [ ] button for delete items
- [ ] button for update items/ edit items

### Task B: CSS

- [x] Added style for the web page

---
## Note:
If you would like, you can add more things on the web page, change the style, ... 
Of course this part is still not finished and we are going to build more on it
